sudo: required
services:
  - docker

before_install:
  - docker build -t envercaliskan/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true envercaliskan/multi-docker npm test

after_success:
  - docker build -t envercaliskan/multi-client ./client
  - docker build -t envercaliskan/multi-nginx ./nginx
  - docker build -t envercaliskan/multi=server ./server
  - docker build -t envercaliskan/multi-worker ./worker
  # Login in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_UD" --password-stdin
  # take those images and push them to dockur hub
  - docker push envercaliskan/multi-client
  - docker push envercaliskan/multi-nginx
  - docker push envercaliskan/multi-server
  - docker push envercaliskan/multi-worker
